service: ${param:department, "promodeagro"}-${param:product, "ecom"}-${param:service, "api"}

frameworkVersion: "4"

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs18.x
  environment:
    PRODUCTS_TABLE: PRODUCTS_TABLE_Testing
  role: arn:aws:iam::851725323791:role/ecommerce_Lambda_Role

  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - "*"
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - DELETE

functions:
  - ${file(products/function.yml)}
resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PRODUCTS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


  # - ${file(webhooks/function.yml)}
plugins:
  - serverless-offline


